### ISSUE TITLE
Review Variable Byte Integer representation in protocol.idl

### ISSUE THREAD

**Issue by jfallows** [reaktivity/nukleus-mqtt.java#5]
See [MQTT 5.0 specification, section 1.5.5](https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901011).

**Comment by dknoma** [comment]
Created new FW `Varbyteuint32FW` to properly represent the variable byte integer. It's an unsigned integer as the valid values for variable byte integer are [0(0x00), 268435455(0xFF 0xFF 0xFF 0x7F)]. `varbyteuint32` was successfully used in place of all `uint8` and `varint32` occurrences for `remainingLength` and `propertiesLength` in `protocol.idl`. `varbyteuint32` acts like any other unsigned integer and cannot be defaulted to null as that can only be done for signed integer types.
